---
title: "Final Project"
format: html
---

# SQL Project

# DRAFT


## Building a Database

build a database using the skills we've covered in the two week course. 


### Data
You will need to find your own (large!) data with at least 3 publicly available tables that have keys connecting them.  Additionally, the data should have some strings that need parsing.

* use the **rvest** package to scrape html data... it will be messy!



### Due Dates
* **Tuesday, January 16**. Email prof with dataset idea for project.  Include the following:
   * Holistic description of the dataset (a few sentences).
   * Explanation of keys that link the data tables.
   * Description of the observational units and columns in each data table. 
   * Full reference for data citation.
   * Link to the resources.

* **End of week 2**. We will have some time in class to work on the project.

* **Tuesday, January 23**. Completed project is due.


## Assignment




1. Input data

2. Describe creation / construction / changing of the DB using DuckDB or MySQL.

3. Some data wrangling in SQL and R (comparison).  Should include some joining.

4. Something with regular expressions

5. Some analysis (probably in R).  Must include at least one visualization.  For fun, you could make a Shiny App (not required).



